/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.zhiku.notify;

import java.io.PrintWriter;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.zhiku.util.RMessage;

/** 
 * MyEclipse Struts
 * Creation date: 05-08-2018
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class ReadNotificationAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		response.setContentType("application/json;charset=utf-8");
		response.setHeader("pragme", "no-cache");
		PrintWriter out = null;
		
		RMessage rmsg = new RMessage();
		try{
			out = response.getWriter();
			
			int nid ;
			try{
				nid = Integer.parseInt(request.getParameter("noticeId"));
			}catch(Exception e){
				nid = -1;
			}
		
			if(nid == -1){
				rmsg.setStatus(300);
				rmsg.setMessage("错误的通知");
			}else{		//检查通知
				Notification nf = NotificationService.getNotificationByNid(nid);
				if(nf == null){
					rmsg.setStatus(300);
					rmsg.setMessage("通知不存在");
				}else{	//	修改通知的状态
					nf.setRead(Notification.READ);
					if(NotificationService.modify(nf)){
						rmsg.setStatus(200);
						rmsg.setMessage("OK");
					}else{
						rmsg.setStatus(300);
						rmsg.setMessage("系统繁忙，请重试！");
					}
				}
				
			}
			
			
		}catch(Exception e){
			rmsg.setStatus(300);
			rmsg.setMessage(e.getCause().toString());
		}finally{
			out.write(RMessage.getJson(rmsg));
			out.flush();
			out.close();
		}
		return null;
	}
}