/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.zhiku.recommend;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.zhiku.user.User;
import com.zhiku.util.Data;
import com.zhiku.util.PythonExe;
import com.zhiku.util.RMessage;

/** 
 * MyEclipse Struts
 * Creation date: 06-11-2018
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class RecommendationAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		response.setContentType("application/json;charset=utf-8");
		response.setHeader("pragme", "no-cache");
		PrintWriter out = null;
		
		RMessage rmsg = new RMessage();
		
		try{
			out = response.getWriter();
			
			
			String username = request.getParameter("username");
			User u = User.findByUsr(username);
			if(u == null ){
				rmsg.setStatus(300);
				rmsg.setMessage("用户不存在!");
				out.write(RMessage.getJson(rmsg));
				return null;
			}
			
			//运行py文件
			int fid = Integer.parseInt(request.getParameter("fid"));
			try{
				PythonExe.Run_Python("/xxx.py", "["+fid+","+u.getUid()+"]");
				PythonExe.Run_Python("/xxx.py", "["+fid+"]");
			}catch(Exception e){
				e.printStackTrace();
				rmsg.setStatus(300);
				rmsg.setMessage("py文件运行失败！");
			}
			
			
			//读取py文件运行后生成的文件
			ArrayList<Data> files = null;
			ArrayList<Data> blogs = null;
			try{
				File file_recommend = new File("/zhiku/智库文档推荐.json");
				if(file_recommend.exists()){
					files = PythonExe.getJson("files", file_recommend);
				}
				File csdn_recommend = new File("/zhiku/csdn.json");
				if(csdn_recommend.exists()){
					blogs = PythonExe.getJson("files", file_recommend);
				}
			}catch(FileNotFoundException fnfe){
				fnfe.printStackTrace();
				rmsg.setStatus(300);
				rmsg.setMessage("文件获取失败！");
			}catch(Exception e){
				e.printStackTrace();
				rmsg.setStatus(300);
				rmsg.setMessage("json解析失败!");
			}
			
			Data data = new Data();
			data.put("files", files);
			data.put("blogs", blogs);
			rmsg.setData(data);
			
			out.write(RMessage.getJson(rmsg));
			
		}catch(Exception e){
			rmsg.setStatus(300);
			rmsg.setMessage(e.getCause().toString());
			out.write(RMessage.getJson(rmsg));
			e.printStackTrace();
		}finally{
			out.flush();
			out.close();
		}
		return null;
		
	}
}