/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.zhiku.action.mail;

import java.io.PrintWriter;
import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.zhiku.user.User;
import com.zhiku.util.RMessage;

/** 
 * MyEclipse Struts
 * Creation date: 04-10-2018
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class FindPwdAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		response.setContentType("application/json;charset=utf-8");
		response.setHeader("pragme", "no-cache");
		response.setHeader("Access-Control-Allow-Credentials", "true");
		response.setHeader("Access-Control-Allow-Origin", request.getHeader("Origin"));
		RMessage rmsg = new RMessage();
		PrintWriter out = null;
		
		try{
			
			String username = request.getParameter("usr");
			long key = Long.parseLong(request.getParameter("key"));
			User u = User.findByUsr(username);
			
			int state = 0;
			//如果用户不存在，或者用户的验证码不正确，则返回错误链接
			if(u == null || key != u.hashCode()+u.getMailtime().getTime()){
				rmsg.setStatus(300);
				rmsg.setMessage("无效的邮件链接!");
			}else {
				Date current = new Date();
				//如果激活时间过期，则返回注册过期
				if(current.compareTo(u.getMailtime()) > 0){
					rmsg.setStatus(300);
					rmsg.setMessage("激活邮件超期失效，请尝试重新请求激活邮件!");
				}else{
					//一切正常,转发到修改页面
					return mapping.findForward("success");
				}
			}
			
			if(state == 0){
				out = response.getWriter();
				out.write(RMessage.getJson(rmsg));
				out.flush();
				out.close();
			}
		}catch(Exception e){
			e.printStackTrace();
		}
		
		return null;
	}
}