/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.zhiku.action.mail;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.zhiku.struts.action.MailCheckAction;
import com.zhiku.struts.action.ReactiveAction;

/** 
 * MyEclipse Struts
 * Creation date: 04-10-2018
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class MailServiceAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String action = request.getParameter("act");
		if("activate".equals(action))
			return new MailCheckAction().execute(mapping, form, request, response);
		if("reacitive".equals(action))
			return new ReactiveAction().execute(mapping, form, request, response);
		if("find_password".equals(action))
			return null;
		return null;
	}
}