/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.zhiku.struts.action;

import java.io.PrintWriter;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.zhiku.file.JFile;
import com.zhiku.util.RMessage;

/** 
 * MyEclipse Struts
 * Creation date: 09-10-2017
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class DeleteFileAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		response.setContentType("application/json;charset=utf-8");
		response.setHeader("pragme", "no-cache");
		PrintWriter out = null;
		
		RMessage rmsg = new RMessage();
		try{
			out = response.getWriter();
			
			String url = request.getRequestURL().toString();
			//根据URL获取fid
			int fid = Integer.parseInt(url.substring(url.lastIndexOf("/")+1, url.lastIndexOf(".")));
			//根据fid找到文件
			JFile f = JFile.findByFid(fid);
			
			if(f != null){
				f.setStatus(JFile.LOCKED);
				if(f.modify()){
					rmsg.setStatus(200);
					rmsg.setMessage("OK");
				}
			}else{
				rmsg.setStatus(300);
				rmsg.setMessage("file not exist!");
			}
			
			out.write(RMessage.getJson(rmsg));
			
		}catch(NumberFormatException nfe){
			rmsg.setStatus(300);
			rmsg.setMessage("Wrong file");
			RMessage.getJson(rmsg);
			nfe.printStackTrace();
		}
		catch(Exception e){
			e.printStackTrace();
		}finally{
			out.flush();
			out.close();
		}
		return null;
	}
}