/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.zhiku.struts.action;

import java.io.PrintWriter;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.zhiku.DB.Transaction;
import com.zhiku.file.JFile;
import com.zhiku.token.Token;
import com.zhiku.user.User;
import com.zhiku.util.RMessage;

/** 
 * MyEclipse Struts
 * Creation date: 09-10-2017
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @author Bao Wei
 * 处理文件的删除请求，删除前应该检查登录状态
 */
public class DeleteFileAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		response.setContentType("application/json;charset=utf-8");
		response.setHeader("pragme", "no-cache");
		response.setHeader("Access-Control-Allow-Credentials", "true");
		response.setHeader("Access-Control-Allow-Origin", request.getHeader("Origin"));
		PrintWriter out = null;
		
		RMessage rmsg = new RMessage();
		try{
			out = response.getWriter();
			
//			//获取用户的session，判断用户的登录状态
//			HttpSession session = request.getSession();
//			int uid = session.getAttribute("uid")==null?-1:(Integer)session.getAttribute("uid");
			
			
			//token验证
			String token = request.getParameter("token");
			if(token != null){
				int status = Token.testToken(token);
				if(status == Token.OVERTIME){
					rmsg.setStatus(401);
					rmsg.setMessage("认证过期，请重新登录!");
					out.write(RMessage.getJson(rmsg));
					return null;
				}else if(status != Token.NORMAL){
					rmsg.setStatus(300);
					rmsg.setMessage("验证失败,请尝试重新登录!");
					out.write(RMessage.getJson(rmsg));
					return null;
				}
			}else{
				rmsg.setStatus(300);
				rmsg.setMessage("请先登录!");
				out.write(RMessage.getJson(rmsg));
				return null;
			}
			
			int uid = (Integer)Token.getPayload(token.substring(token.indexOf('.')+1, token.lastIndexOf('.'))).get("uid");

			User u = User.findByUid(uid);
			
			if (uid == -1 && u == null){
				rmsg.setStatus(300);
				rmsg.setMessage("请先登录!");
				out.write(RMessage.getJson(rmsg));;
				return null;
			}
			
			String url = request.getRequestURL().toString();
			//根据URL获取fid
			int fid = Integer.parseInt(url.substring(url.lastIndexOf("/")+1, url.lastIndexOf(".")));
			//根据fid找到文件
			JFile f = JFile.findByFid(fid);
			
			if(f != null){	//文件存在
				if(f.getUpuid() == u.getUid()){	//文件是该用户上传
					if(Transaction.deleteFile(f, u)){	//删除操作完成
						rmsg.setStatus(200);
						rmsg.setMessage("OK");
					}else{
						rmsg.setStatus(300);
						rmsg.setMessage("发生了一个意料之外的错误!");
					}
				}else{
					rmsg.setStatus(300);
					rmsg.setMessage("你没有权限,需要帮助请联系管理员!");
				}
			}else{
				rmsg.setStatus(300);
				rmsg.setMessage("文件不存在!");
			}
			
			out.write(RMessage.getJson(rmsg));
			
		}catch(NumberFormatException nfe){
			rmsg.setStatus(300);
			rmsg.setMessage("文件出错!");
			out.write(RMessage.getJson(rmsg));;
			nfe.printStackTrace();
		}
		catch(Exception e){
			e.printStackTrace();
		}finally{
			out.flush();
			out.close();
		}
		return null;
	}
}