/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.zhiku.struts.action;

import java.io.PrintWriter;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.zhiku.file.JFile;
import com.zhiku.util.RMessage;

/** 
 * MyEclipse Struts
 * Creation date: 09-01-2017
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class FileModifyAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		response.setContentType("application/json;charset=utf-8");
		response.setHeader("pragme", "no-cache");
		PrintWriter out = null;
		
		RMessage rmsg = new RMessage();
		try{
			out = response.getWriter();
			
			String url = request.getRequestURL().toString();
			//根据URL获取fid
			int fid = Integer.parseInt(url.substring(url.lastIndexOf("/")+1, url.lastIndexOf(".")));
			//根据fid找到文件
			JFile f = JFile.findByFid(fid);
			
			//从前端获取修改信息
			String name = request.getParameter("name");
			int module = Integer.parseInt(request.getParameter("module"));
			String teacher = request.getParameter("teacher");
			int course = Integer.parseInt(request.getParameter("course"));
			int docformat = Integer.parseInt(request.getParameter("docformat"));
			String fileformat = request.getParameter("fileformat");
//			int upuid = Integer.parseInt(request.getParameter("upuid"));	//不建议对文件的上传者修改
			int origin = Integer.parseInt(request.getParameter("origin"));
			String desc = request.getParameter("desc");
			
			//设置文件的新属性
			f.setName(name);
			f.setModule(module);
			f.setTeacher(teacher);
			f.setCourse(course);
			f.setDocformat(docformat);
			f.setFileformat(fileformat);
//			f.setUpuid(upuid);
			f.setOrigin(origin);
			f.setDesc(desc);
			
			if(f.modify()){
				rmsg.setStatus(200);
				rmsg.setMessage("OK");
			}else{
				rmsg.setStatus(300);
				rmsg.setMessage("Fail,please try again!");
			}
			
			out.write(RMessage.getJson(rmsg));
			
		}catch(NumberFormatException ne){
			//如果fid出现问题，则捕获这个异常
			rmsg.setStatus(300);
			rmsg.setMessage("Wrong fid");
			out.write(RMessage.getJson(rmsg));
		}catch(Exception e){
			e.printStackTrace();
		}finally{
			out.flush();
			out.close();
		}
		return null;
	}
}