/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.zhiku.struts.action;

import java.io.PrintWriter;
import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.zhiku.DB.Transaction;
import com.zhiku.file.JFile;
import com.zhiku.file.operation.FileOP;
import com.zhiku.file.operation.FileOPService;
import com.zhiku.util.FileUpDownLoad;
import com.zhiku.util.RMessage;

/** 
 * MyEclipse Struts
 * Creation date: 09-03-2017
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class FileDownloadAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		PrintWriter out = null;
		
		RMessage rmsg = new RMessage();
		try{
			
			String url = request.getRequestURL().toString();
			//根据URL获取fid
			int fid = Integer.parseInt(url.substring(url.lastIndexOf("/")+1, url.lastIndexOf(".")));
			System.out.println(fid);
			//根据fid找到对应文件的信息
			JFile f = JFile.findByFid(fid);
			
			FileUpDownLoad filedownload = new FileUpDownLoad();
			filedownload.download(this.getServlet(), request, response, f);
			//更改文件下载量信息
			f.setDncnt(f.getDncnt() + 1);
			f.modify();
			//记录下载操作
			FileOP fp = new FileOP();
			fp.setFid(fid);
			HttpSession session = request.getSession();
			int uid;
			try {
				uid = (Integer) session.getAttribute("uid");
			} catch (Exception e) {
				out = response.getWriter();
				rmsg.setStatus(300);
				rmsg.setMessage("you haven't login!");
				out.write(RMessage.getJson(rmsg));
				e.printStackTrace();
				return null;
			}
			fp.setUid(uid);
			fp.setType(FileOP.DOWNLOAD);
			fp.setOptime(new Date());
			String opip = request.getHeader("x-forwarded-for") == null? request.getRemoteAddr():request.getHeader("x-forwarded-for");
			fp.setOpip(opip);
			Transaction.saveFileOP(fp);
			//设置返回信息
			out = response.getWriter();
			rmsg.setStatus(200);
			rmsg.setMessage("OK");
			out.write(RMessage.getJson(rmsg));
		}catch(NumberFormatException ne){
			//如果uid出现问题，则捕获这个异常
			rmsg.setStatus(300);
			rmsg.setMessage("Wrong fid");
			out.write(RMessage.getJson(rmsg));
		}catch(Exception e){
			e.printStackTrace();
		}finally{
			out.flush();
			out.close();
		}
		return null;
	}
}