/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.zhiku.struts.action;

import java.io.PrintWriter;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.zhiku.activity.Activity;
import com.zhiku.activity.ActivityService;
import com.zhiku.util.Data;
import com.zhiku.util.RMessage;

/** 
 * MyEclipse Struts
 * Creation date: 03-20-2018
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class GetNewsAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		response.setContentType("application/json;charset=utf-8");
		response.setHeader("pragme", "no-cache");
		PrintWriter out = null;
		
		RMessage rmsg = new RMessage();
		try{
			out = response.getWriter();
			
			int num = request.getParameter("number")==null?Activity.ACTIVITY_NUM:Integer.parseInt(request.getParameter("number"));
			List<Activity> acts = ActivityService.getNews(num);
			
			if(acts != null){
				List<Data> data = new ArrayList<Data>();
				Data d = null;
				for(Activity a:acts){
					d = new Data();
					d.put("url", a.getImg());
					d.put("date", new SimpleDateFormat("yyyy-MM-dd HH:mm").format(a.getPubtime()));
					d.put("details", a.getDescs());
					d.put("title", a.getTitle());
					d.put("linkweb", a.getLinkweb());
					d.put("scancnt", a.getScancnt());
					d.put("username", a.getUsername());
					
					data.add(d);
				}
				rmsg.setData(data);
			}
			
			rmsg.setStatus(200);
			rmsg.setMessage("OK");
			out.write(RMessage.getJson(rmsg));
			
		}catch(Exception e){
			rmsg.setStatus(300);
			rmsg.setMessage(e.getCause().toString());
		}finally{
			out.flush();
			out.close();
		}
		return null;
	}
}