/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.zhiku.struts.action;

import java.io.PrintWriter;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.zhiku.token.Token;
import com.zhiku.user.UserView;
import com.zhiku.util.Data;
import com.zhiku.util.RMessage;

/** 
 * MyEclipse Struts
 * Creation date: 09-19-2017
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class GetUserInfoAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		response.setContentType("application/json;charset=utf-8");
		response.setHeader("pragme", "no-cache");
		response.setHeader("Access-Control-Allow-Credentials", "true");
		response.setHeader("Access-Control-Allow-Origin", request.getHeader("Origin"));
		PrintWriter out = null;
		
		RMessage rmsg = new RMessage();
		try{
			out = response.getWriter();
			
//			//获取用户的session，判断用户的登录状态
//			HttpSession session = request.getSession();
//			int uid = session.getAttribute("uid")==null?-1:(Integer)session.getAttribute("uid");
//			
//			if (uid == -1){
//				rmsg.setStatus(300);
//				rmsg.setMessage("请先登录!");
//				out.write(RMessage.getJson(rmsg));;
//				return null;
//			}
			
			//token验证
			String token = request.getParameter("token");
			if(token != null){
				int status = Token.testToken(token);
				if(status == Token.OVERTIME){
					rmsg.setStatus(401);
					rmsg.setMessage("认证过期，请重新登录!");
					out.write(RMessage.getJson(rmsg));
					return null;
				}else if(status != Token.NORMAL){
					rmsg.setStatus(300);
					rmsg.setMessage("验证失败,请尝试重新登录!");
					out.write(RMessage.getJson(rmsg));
					return null;
				}
			}else{
				rmsg.setStatus(300);
				rmsg.setMessage("请先登录!");
				out.write(RMessage.getJson(rmsg));
				return null;
			}
			
			int uid = (Integer)Token.getPayload(token.substring(token.indexOf('.')+1, token.lastIndexOf('.'))).get("uid");
			
			//根据URL获取username
			String url = request.getRequestURL().toString();
			String username = url.substring(url.lastIndexOf("/")+1, url.lastIndexOf("."));
			UserView uv = UserView.getUserInfo(username);
			//如果用户不存在
			if(uv == null || uv.getUid() != uid){
				rmsg.setStatus(300);
				rmsg.setMessage("用户不存在!");
				out.write(RMessage.getJson(rmsg));
				return null;
			}
			
			//设置返回信息
			Data data = new Data();
			data.put("uid",uv.getUid());
			data.put("username", uv.getUsr());
			data.put("nickname", uv.getNick());
//			data.put("avator", uv.getAvator());
			data.put("sign", uv.getSign());
			data.put("coin", uv.getCoin());
			data.put("mail", uv.getMail());
			data.put("phone", uv.getPhone());
			data.put("qq", uv.getQq());
			data.put("xname", uv.getXname());
			data.put("mname", uv.getMname());
			data.put("auth", uv.getAuth());
			data.put("status", uv.getStatus());
			data.put("uploadcount", uv.getUpcnt());
			data.put("downloadcount", uv.getDncnt());
			data.put("collectcount",uv.getColcnt());
			
			rmsg.setStatus(200);
			rmsg.setMessage("OK");
			rmsg.setData(data);
			out.write(RMessage.getJson(rmsg));
			
			
		}catch(Exception e){
			rmsg.setStatus(300);
			rmsg.setMessage(e.getCause().toString());
			out.write(RMessage.getJson(rmsg));
			e.printStackTrace();
		}finally{
			out.flush();
			out.close();
		}
		return null;
	}
}