/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.zhiku.struts.action;

import java.io.PrintWriter;

import javax.servlet.http.Cookie;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.codec.digest.DigestUtils;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.zhiku.user.User;
import com.zhiku.util.RMessage;

/** 
 * MyEclipse Struts
 * Creation date: 08-21-2017
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class LoginAction extends Action {
	
	public static final int OVER_TIME  = 30*60;
	
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		response.setContentType("application/json;charset=utf-8");
		response.setHeader("pragme", "no-cache");
		PrintWriter out = null;
		
		RMessage rmsg = new RMessage();
		try{
			out = response.getWriter();
			
			String usr = request.getParameter("username");
			String pwd = DigestUtils.md5Hex(request.getParameter("password"));
			
			if(User.check(usr, pwd)){
				User u = User.findByUsr(usr);
				if(u.getStatus() == User.NORMAL){
					rmsg.setStatus(200);
					rmsg.setMessage("OK");
					//将uid的值放到session中
					HttpSession session = request.getSession();
					session.setMaxInactiveInterval(OVER_TIME);	//设置session的有效时间为30min
					session.setAttribute("uid", u.getUid());
					Cookie cookie = new Cookie("username",u.getUsr());
					cookie.setMaxAge(OVER_TIME);
					cookie.setPath("/");
					response.addCookie(cookie);
				}else if(u.getStatus() == User.UNACTIVE){
					rmsg.setStatus(300);
					rmsg.setMessage("Sorry ,your e-mail doesn't check!");
				}else {
					rmsg.setStatus(300);
					rmsg.setMessage("Sorry ,you have been locked!");
				}
			}else{
				rmsg.setStatus(300);
				rmsg.setMessage("Username or password wrong");
			}
			
			out.write(RMessage.getJson(rmsg));
			
		}catch(Exception e){
			e.printStackTrace();
		}finally{
			out.flush();
			out.close();
		}
		return null;
	}
}