/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.zhiku.struts.action;

import java.io.PrintWriter;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.zhiku.file.FileView;
import com.zhiku.util.Data;
import com.zhiku.util.RMessage;
import com.zhiku.xmc.XMCService;

/** 
 * MyEclipse Struts
 * Creation date: 08-26-2017
 * 处理关键字搜索文件的action
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class SearchDocumentAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		response.setContentType("application/json;charset=utf-8");
		response.setHeader("pragme", "no-cache");
		PrintWriter out = null;
		
		RMessage rmsg = new RMessage();
		try{
			out = response.getWriter();
			int method = Integer.parseInt(request.getParameter("method"));
			int xid = Integer.parseInt(request.getParameter("college"));
			int mid = Integer.parseInt(request.getParameter("major"));
			int cid = Integer.parseInt(request.getParameter("course"));
			
			if(!XMCService.isExist("Major", "mid", mid)){	//如果不存在则返回非法专业
				rmsg.setStatus(300);
				rmsg.setMessage("Invalid major");
				out.write(RMessage.getJson(rmsg));
				return null;
			}
			
			if(!XMCService.isExist("Course", "cid", cid)){	//如果课程不存在则返回非法课程
				rmsg.setStatus(300);
				rmsg.setMessage("Invalid course");
				out.write(RMessage.getJson(rmsg));
				return null;
			}
			
			List<FileView> filelist = null;
			
			//根据不同的搜索方式，给filelist赋值
			if(method == 1){	//关键字搜索
				filelist = FileView.findByCid(cid);
			}else if(method == 2){  	//学院专业搜索
				filelist = FileView.findByCids(XMCService.findCoursesInXM(xid, mid));
			}
			
			//设置返回的data信息
			Data[] data = new Data[filelist.size()];
			int index = 0;
			for(FileView f : filelist){
				data[index].put("fid", f.getFid());
				data[index].put("upuid", f.getUid());
				
				Data fileinfo = new Data();
				fileinfo.put("name", f.getName());
				fileinfo.put("module", f.getModule());
				fileinfo.put("course", f.getCname());
				fileinfo.put("docformat", f.getDocformat());
				fileinfo.put("origin", f.getOrigin());
				fileinfo.put("uptime", f.getUptime());
				fileinfo.put("desc", f.getDesc());
				data[index].put("fileinfo", fileinfo);
				
				Data upperinfo = new Data();
				upperinfo.put("nickname", f.getNick());
				upperinfo.put("xname", f.getXname());
				upperinfo.put("mname", f.getMname());
				data[index].put("upperinfo", upperinfo);
				
				index++;
			}
			
			rmsg.setStatus(200);
			rmsg.setMessage("OK");
			rmsg.setData(data);
			out.write(RMessage.getJson(rmsg));
			
		}catch(Exception e){
			e.printStackTrace();
		}finally{
			out.flush();
			out.close();
		}
		return null;
	}
}