/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.zhiku.struts.action;

import java.io.PrintWriter;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.zhiku.file.FileView;
import com.zhiku.file.JFile;
import com.zhiku.user.User;
import com.zhiku.util.Data;
import com.zhiku.util.RMessage;

/** 
 * MyEclipse Struts
 * Creation date: 08-26-2017
 * 处理关键字搜索文件的action
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class SearchDocumentAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		response.setContentType("application/json;charset=utf-8");
		response.setHeader("pragme", "no-cache");
		PrintWriter out = null;
		
		RMessage rmsg = new RMessage();
		try{
			out = response.getWriter();
			
			int cid = Integer.parseInt(request.getParameter("course"));
			List<FileView> filelist = FileView.findByCid(cid);
			
			Data[] data = new Data[filelist.size()];
			int index = 0;
			for(FileView f : filelist){
				data[index].put("fid", f.getFid());
				data[index].put("upuid", f.getUid());
				
				Data fileinfo = new Data();
				fileinfo.put("name", f.getName());
				fileinfo.put("module", f.getModule());
				fileinfo.put("course", f.getCname());
//				fileinfo.put("docformat", f.getDocformat());	//个人感觉不需要提供这个属性，文件名中包含后缀，不要刻意提取
				fileinfo.put("origin", f.getOrigin());
				fileinfo.put("uptime", f.getUptime());
				fileinfo.put("desc", f.getDesc());
				data[index].put("fileinfo", fileinfo);
				
				Data upperinfo = new Data();
				upperinfo.put("nickname", f.getNick());
//				upperinfo.put("xid", f.getXid());	//个人感觉没有必要提供
				upperinfo.put("xname", f.getXname());
//				upperinfo.put("mid", f.getMid());	//个人感觉没有必要提供
				upperinfo.put("mname", f.getMname());
				data[index].put("upperinfo", upperinfo);
				
				index++;
			}
			
			rmsg.setStatus(200);
			rmsg.setMessage("OK");
			rmsg.setData(data);
			
		}catch(Exception e){
			rmsg.setStatus(300);
			rmsg.setMessage("wrong , please try again");
			e.printStackTrace();
		}finally{
			out.write(RMessage.getJson(rmsg));
			out.flush();
			out.close();
		}
		return null;
	}
}