/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.zhiku.struts.action;

import java.io.PrintWriter;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.commons.codec.digest.DigestUtils;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.zhiku.user.User;
import com.zhiku.util.RMessage;

/** 
 * MyEclipse Struts
 * Creation date: 09-01-2017
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class UserInfoModifyAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		response.setContentType("application/json;charset=utf-8");
		response.setHeader("pragme", "no-cache");
		PrintWriter out = null;
		
		RMessage rmsg = new RMessage();
		try{
			out = response.getWriter();
			
			String url = request.getRequestURL().toString();
			//根据URL获取uid
			int uid = Integer.parseInt(url.substring(url.lastIndexOf("/")+1, url.lastIndexOf(".")));
			//根据uid找到当前用户的信息
			User u = User.findByUid(uid);
			//获取前端的信息
			String oldpwd = request.getParameter("oldpwd");
			if(u.getPwd().equals(DigestUtils.md5Hex(oldpwd))){	//如果密码验证正确，继续信息修改的操作
				//获取剩下的信息
				String nickname = request.getParameter("nickname");
				String newpwd = request.getParameter("newpwd");
//				String avator = request.getParameter("avator");
				String phone = request.getParameter("phone");
				String qq = request.getParameter("qq");
				int xid = Integer.parseInt(request.getParameter("xid"));
				int mid = Integer.parseInt(request.getParameter("mid"));
				
				//设置这些信息
				u.setNick(nickname);
				u.setPwd(DigestUtils.md5Hex(newpwd));
//				u.setAvator(avator);
				u.setPhone(phone);
				u.setQq(qq);
				u.setXid(xid);
				u.setMid(mid);
				
				if(u.modify()){
					rmsg.setStatus(200);
					rmsg.setMessage("OK");
				}else{
					rmsg.setStatus(300);
					rmsg.setMessage("Fail,please try again!");
				}
				
			}else{
				rmsg.setStatus(300);
				rmsg.setMessage("Wrong password");
			}
			
			out.write(RMessage.getJson(rmsg));
			
		}catch(NumberFormatException ne){
			//如果uid出现问题，则捕获这个异常
			rmsg.setStatus(300);
			rmsg.setMessage("Wrong uid");
			out.write(RMessage.getJson(rmsg));
		}catch(Exception e){
			e.printStackTrace();
		}finally{
			out.flush();
			out.close();
		}
		return null;
	}
}